$(document).ready(function(){
    $('#vid').click(function(){
        $('#yt').slideToggle();
    });
    $('#jbahan').click(function(){
        $('#bahan').slideToggle();
    });
    $('#jInstruksi').click(function(){
        $('#instruksi').slideToggle();
    });
});
